import React from 'react'


export const wellColumns = [{
          Header: 'ID',
          accessor: 'id',
          Width: 175,
          sortable: false
        }, {
          Header: 'SideTrackID',
          accessor: 'sideTrackID',
          Width: 175
        }, {
          Header: 'WellName',
          accessor: 'wellName',
          Width: 175
        }, {
          Header: 'WellType',
          accessor: 'wellType',
          Width: 175
        }, {
          Header: 'ClientDepth2',
          accessor: 'clientDepth2',
          Width: 175
        }, {
          Header: 'QRIDepth2',
          accessor: 'qriDepth2',
          Width: 175
        }, {
          Header: 'QRIDepthRevised',
          accessor: 'qriDepthRevised',
          Width: 175
        }, {
          Header: 'ClientHoleSize',
          accessor: 'clientHoleSize',
          Width: 175
        }, {
          Header: 'QRIHoleSize',
          accessor: 'qriHoleSize',
          Width: 175
        }, {
          Header: 'QRIHoleSizeRevised',
          accessor: 'qriHoleSizeRevised',
          Width: 175
        }, {
          Header: 'OperationDate',
          accessor: 'operationDate',
          Width: 175
        }, {
          Header: 'FromDateTime',
          accessor: 'fromDateTime',
          Width: 175
        }, {
          Header: 'ToDateTime',
          accessor: 'toDateTime',
          Width: 175
        }, {
          Header: 'DateCheck',
          accessor: 'dateCheck',
          Width: 175
        }, {
          Header: 'DurationDays',
          accessor: 'durationDays',
          Width: 175
        }, {
          Header: 'TimeCheck',
          accessor: 'timeCheck',
          Width: 175
        }, {
          Header: 'Footage',
          accessor: 'footage',
          Width: 175
        }, {
          Header: 'ROPM_hr',
          accessor: 'ropmHr',
          Width: 175
        }, {
          Header: 'DFS',
          accessor: 'dfs',
          Width: 175
        }, {
          Header: 'ActivityDescription',
          accessor: 'description',
          Width: 175
        }, {
          Header: 'ActivityDescriptionEnglish',
          accessor: 'descriptionEnglish',
          Width: 175
        }, {
          Header: 'ClientP_NP',
          accessor: 'clientP_NP',
          Width: 175
        }, {
          Header: 'QRIRevisedP_NP',
          accessor: 'qriP_NPRevised',
          Width: 175
        }, {
          Header: 'Probability',
          accessor: 'prob',
          Width: 175
        }, {
          Header: 'ClientPhase',
          accessor: 'clientPhase',
          Width: 175
        }, {
          Header: 'QRIMajorOperation',
          accessor: 'qriMajorOperation',
          Width: 175
        }, {
          Header: 'NPTCategory',
          accessor: 'nptCategory',
          Width: 175
        }, {
          Header: 'NPTType',
          accessor: 'nptType',
          Width: 175
        }]